# THIS IS A SAMPLE ".tas.yml" CONFIGURATION FILE.
# FIRSTLY - You need to specify which testing framework you are using. Currently supported JS frameworks are : mocha, jest and jasmine.
version: 2.0.0
postMerge :    
  submodules:
    - name: package-1
      path : "./"
      pattern:
        # glob-patterns to discover tests to run in case of postMerge
        - ""
      framework : golang
      preRun: 
        runEveryTime: false # if set to true it will run on test execution as well
        command:
            - "go get -d ./..."
            - "go mod vendor"
preMerge :
  submodules:
    - name: package-1
      path : "./"
      pattern:
        # glob-patterns to discover tests to run in case of postMerge
        - ""
      framework : golang
      preRun: 
        runEveryTime: false # if set to true it will run on test execution as well
        command:
            - "go get -d ./..."
            - "go mod vendor"
